name: has-constraint-th
version: 0.1.0
category: Control
author: Christian Kjaer Laustsen
maintainer: ckl@codetalk.io
license: BSD3
github: Tehnix/has-constraint

extra-source-files:
- README.md

dependencies:
  - base >= 4.8
  - template-haskell >= 2.11

library:
  source-dirs: src
  default-extensions:
  - ConstraintKinds
  - Rank2Types
  - FlexibleInstances
  - FlexibleContexts
  - TemplateHaskell

tests:
  test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.8
    - has-constraint
    - QuickCheck
    - tasty >= 0.7
    - tasty-quickcheck
